# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d38d8f5c09274722b42b8e8b69eaccdeb0a41c18a5e2e98f0f9146cebe472c9931e964896b62b90e4a14de29927f8853ee7190464663ed2404eb6d50a292048


test:
  secret_key_base: f3ee72b3eb4999067c51f28fe676e21111a1e0c5be20df9885474c25c6bca686c890b0f4fe7f9e4f7cc8c0b9362dcf40bf38b79bb48f99a0c17d60a0b4bfa4cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
